#ifndef __CRSF_PROTOCOL_H
#define __CRSF_PROTOCOL_H

#define CRSF_FRAME_HEADER 0xC8

#define CRSF_FRAME_SIZE_MAX 64
#define CRSF_FRAME_SIZE_MINIMAL 2

#define CRSF_FRAME_TYPE_RC_CHANNELS 0X16
#define CRSF_FRAME_TYPE_LINK_STATISTICS 0X14
#define CRSF_FRAME_TYPE_BATTERY_SENSOR 0X08
#define CRSF_FRAME_TYPE_GPS 0x02
#define CRSF_FRAME_TYPE_ATTITUDE 0x1E
#define CRSF_FRAME_TYPE_FLIGHT_MODE 0x21

#define CRSF_FRAME_PAYLOAD_LENGTH_GPS 15
#define CRSF_FRAME_PAYLOAD_LENGTH_BATTERY 8
#define CRSF_FRAME_PAYLOAD_LENGTH_ATTITUDE  6
#define CRSF_FRAME_PAYLOAD_LENGTH_RC_CHANNEL 22


// 设备地址 (CRSF 总线地址)
#define CRSF_ADDRESS_BROADCAST             0x00
#define CRSF_ADDRESS_FLIGHT_CONTROLLER     0xC8 // 飞控
#define CRSF_ADDRESS_RADIO_TRANSMITTER     0xEA // 遥控器主板 (Source)
#define CRSF_ADDRESS_CRSF_RECEIVER         0xEC // 接收机
#define CRSF_ADDRESS_CRSF_TRANSMITTER      0xEE // 高频头 (Destination)

// 扩展帧类型
#define CRSF_FRAME_TYPE_DEVICE_PING              0x28
#define CRSF_FRAME_TYPE_DEVICE_INFO              0x29
#define CRSF_FRAME_TYPE_PARAMETER_SETTINGS_ENTRY 0x2B // 高频头返回的参数数据
#define CRSF_FRAME_TYPE_PARAMETER_READ           0x2C // 主板发出的读取请求
#define CRSF_FRAME_TYPE_PARAMETER_WRITE          0x2D // 主板发出的写入请求
// (如果有用到 0x3A 也可以顺手加上，防止以后不认识)
#define CRSF_FRAME_TYPE_RADIO_ID                 0x3A

#define CRSF_ADDRESS_BROADCAST         0x00
#define CRSF_ADDRESS_FLIGHT_CONTROLLER 0xC8
#define CRSF_ADDRESS_RADIO_TRANSMITTER 0xEA
#define CRSF_ADDRESS_CRSF_RECEIVER     0xEC
#define CRSF_ADDRESS_CRSF_TRANSMITTER  0xEE

#endif
