#ifndef __CRSF_PROTOCOL_H
#define __CRSF_PROTOCOL_H

#define CRSF_FRAME_HEADER 0xC8

#define CRSF_FRAME_SIZE_MAX 64
#define CRSF_FRAME_SIZE_MINIMAL 2

#define CRSF_FRAME_TYPE_RC_CHANNELS 0X16
#define CRSF_FRAME_TYPE_LINK_STATISTICS 0X14
#define CRSF_FRAME_TYPE_BATTERY_SENSOR 0X08
#define CRSF_FRAME_TYPE_GPS 0x02
#define CRSF_FRAME_TYPE_ATTITUDE 0x1E
#define CRSF_FRAME_TYPE_FLIGHT_MODE 0x21

#define CRSF_FRAME_PAYLOAD_LENGTH_GPS 15
#define CRSF_FRAME_PAYLOAD_LENGTH_BATTERY 8
#define CRSF_FRAME_PAYLOAD_LENGTH_ATTITUDE  6

#endif
