#include "gpio/ll_gpio_sdio.h"
#include "sys_hardware_config.h"
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"

void gpio_sdio_init(void)
{
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOC);
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOD);
    
    LL_GPIO_SetPinMode(HW_SDIO_CK_PORT, HW_SDIO_CK_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_CK_PORT, HW_SDIO_CK_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_CK_PORT, HW_SDIO_CK_PIN, LL_GPIO_PULL_NO);
    LL_GPIO_SetAFPin_8_15(HW_SDIO_CK_PORT, HW_SDIO_CK_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_CK_PORT, HW_SDIO_CK_PIN, LL_GPIO_OUTPUT_PUSHPULL);

    LL_GPIO_SetPinMode(HW_SDIO_D0_PORT, HW_SDIO_D0_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_D0_PORT, HW_SDIO_D0_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_D0_PORT, HW_SDIO_D0_PIN, LL_GPIO_PULL_UP);   
    LL_GPIO_SetAFPin_8_15(HW_SDIO_D0_PORT, HW_SDIO_D0_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_D0_PORT, HW_SDIO_D0_PIN, LL_GPIO_OUTPUT_PUSHPULL);
 
    LL_GPIO_SetPinMode(HW_SDIO_D1_PORT, HW_SDIO_D1_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_D1_PORT, HW_SDIO_D1_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_D1_PORT, HW_SDIO_D1_PIN, LL_GPIO_PULL_UP);   
    LL_GPIO_SetAFPin_8_15(HW_SDIO_D1_PORT, HW_SDIO_D1_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_D1_PORT, HW_SDIO_D1_PIN, LL_GPIO_OUTPUT_PUSHPULL);
 
    LL_GPIO_SetPinMode(HW_SDIO_D2_PORT, HW_SDIO_D2_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_D2_PORT, HW_SDIO_D2_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_D2_PORT, HW_SDIO_D2_PIN, LL_GPIO_PULL_UP);   
    LL_GPIO_SetAFPin_8_15(HW_SDIO_D2_PORT, HW_SDIO_D2_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_D2_PORT, HW_SDIO_D2_PIN, LL_GPIO_OUTPUT_PUSHPULL);
  
    LL_GPIO_SetPinMode(HW_SDIO_D3_PORT, HW_SDIO_D3_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_D3_PORT, HW_SDIO_D3_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_D3_PORT, HW_SDIO_D3_PIN, LL_GPIO_PULL_UP);   
    LL_GPIO_SetAFPin_8_15(HW_SDIO_D3_PORT, HW_SDIO_D3_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_D3_PORT, HW_SDIO_D3_PIN, LL_GPIO_OUTPUT_PUSHPULL);
   
    LL_GPIO_SetPinMode(HW_SDIO_CMD_PORT, HW_SDIO_CMD_PIN, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinSpeed(HW_SDIO_CMD_PORT, HW_SDIO_CMD_PIN, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinPull(HW_SDIO_CMD_PORT, HW_SDIO_CMD_PIN, LL_GPIO_PULL_UP);   
    LL_GPIO_SetAFPin_0_7(HW_SDIO_CMD_PORT, HW_SDIO_CMD_PIN, HW_SDIO_GPIO_AF);
    LL_GPIO_SetPinOutputType(HW_SDIO_CMD_PORT, HW_SDIO_CMD_PIN, LL_GPIO_OUTPUT_PUSHPULL);
}
